### ISSUE TITLE
unable to run.

### ISSUE THREAD

**Issue by upperhill** [Changaco/xmpputils#5]
I installed sleekxmpp and dnspython

can you give an example of a working command?

```
./sendxmpp.py -c ~/.xmpputils -s "this is a test" user@host
```
this doesn't work

**Comment by Changaco** [comment]
echo "this is a test" | ./sendxmpp.py user@host

**Comment by upperhill** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dns/resolver.py", line 157, in __init__
    rdclass, rdtype)
  File "/usr/lib/python3.4/site-packages/dns/message.py", line 333, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dns/resolver.py", line 167, in __init__
    dns.rdatatype.CNAME)
  File "/usr/lib/python3.4/site-packages/dns/message.py", line 333, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sendxmpp.py", line 85, in <module>
    if xmpp.connect():
  File "/usr/lib/python3.4/site-packages/sleekxmpp/clientxmpp.py", line 160, in connect
    reattempt=reattempt)
  File "/usr/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 448, in connect
    args=(reattempt,))
  File "/usr/lib/python3.4/site-packages/sleekxmpp/thirdparty/statemachine.py", line 70, in transition
    func=func, args=args, kwargs=kwargs)
  File "/usr/lib/python3.4/site-packages/sleekxmpp/thirdparty/statemachine.py", line 111, in transition_any
    return_val = func(*args,**kwargs) if func is not None else True
  File "/usr/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 484, in _connect
    self.address[1])
  File "/usr/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1107, in pick_dns_answer
    return next(self.dns_answers)
  File "/usr/lib/python3.4/site-packages/sleekxmpp/xmlstream/resolver.py", line 148, in resolve
    use_dnspython=use_dnspython):
  File "/usr/lib/python3.4/site-packages/sleekxmpp/xmlstream/resolver.py", line 242, in get_AAAA
    recs = resolver.query(host, dns.rdatatype.AAAA)
  File "/usr/lib/python3.4/site-packages/dns/resolver.py", line 956, in query
    raise_on_no_answer)
  File "/usr/lib/python3.4/site-packages/dns/resolver.py", line 176, in __init__
    raise NoAnswer(question=response.question)
  File "/usr/lib/python3.4/site-packages/dns/exception.py", line 47, in __init__
    self._check_kwargs(**kwargs)
  File "/usr/lib/python3.4/site-packages/dns/exception.py", line 69, in _check_kwargs
    self.supp_kwargs)
AssertionError: following set of keyword args is required: {'response'}

**Comment by Changaco** [comment]
Looks like a bug in dnspython, which version is it?

**Comment by upperhill** [comment]
I compiled from git.

**Comment by Changaco** [comment]
Then I suggest trying a stable version.

**Comment by upperhill** [comment]
Thanks, I installed dnspython-1.12.0-py3 and it worked!
